name: Build and test

on:
  push:
    branches: [develop, live]

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm test
        run: |
          npm test
        env:
          CI: true
      - name: Code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/
  build:
    name: Build and package
    runs-on: ubuntu-latest
    if: ${{ endsWith(github.ref, 'live') }}
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: npm pack
        run: |
          npm pack
        env:
          CI: true
      - name: Upload npm package
        uses: actions/upload-artifact@v2
        with:
          name: npm-package
          path: ./*.tgz
